languageCode = "en-us"
title = "Tom and Georgie | 18 August 2017"
baseurl = "http://www.tomandgeorgie.co.uk/"
theme = "hugo-smpl-theme"
canonifyURLs = false

googleAnalytics = "UA-89723923-1"

[[menu.main]]
  name = "Home"
  url = ""
  weight = 1
[[menu.main]]
  name = "RSVP"
  url = "rsvp"
  weight = 2
[[menu.main]]
  name = "Info"
  url = "info"
  weight = 3
[[menu.main]]
  name = "Accommodation"
  url = "accommodation"
  weight = 4
[[menu.main]]
  name = "Giftlist"
  url = "giftlist"
  weight = 5

[params]
  name = "Tom Barrett"
  description = "Tom and Georgie's wedding site"

  # Custom files
  custom_css = ["assets/css/main.css", "assets/css/custom.css"]
  custom_js = []

  # Background
  [params.background]
    image = "images/tree_compressed.png"

  # Teddy image
  [params.teddy]
    image = "bear_smaller.png"

  # Enable and set background fade speed
  [params.background.fade]
    enable = true
    speed = 500

  # Header section
  [params.header]
    enable = true
    title = "Tom and Georgie: 18 August 2017"

  # Quote section
  [params.quote]
    enable = true
    lines = ["18th August 2017", "Merton College, Oxford"]

  # Button
  [params.buttons]
    enable = true

  [[params.button]]
    title = "RSVP"
    link = "/rsvp"
